//
// Created by TakumiYamashita on 2018/06/10.
//

#ifndef DEEP_LEARNING_FROM_SCRATCH_PRIMITIVE_HPP
#define DEEP_LEARNING_FROM_SCRATCH_PRIMITIVE_HPP

#endif //DEEP_LEARNING_FROM_SCRATCH_PRIMITIVE_HPP
